### PR TITLE
Brand guides

### PR DESCRIPTION
**Pull request by maciejmatu**

### CODE REVIEW

**Comment by blrhc** [comment]
Hi @maciejmatu, am reviewing this now.

**Comment by blrhc** [comment]
Hi @maciejmatu, I guess I'll give some general feedback on the story page only as the other two need significantly more work.

Try to avoid this kind of thing when the page is resized, the font size needs to adjust to the screen:
brandpage1

Equally, in the other direction, things shouldn't adjust so much as to generate lots of empty space.
brandpage2

Just general things to consider, please do let me know when you think this page is ready to take a look at, and as soon as the other ones are good I can also provide some feedback on those.

I understand that it's not always easy to estimate, but when do you think you might have all of the branding pages ready for review?

**Comment by maciejmatu** [comment]
Thanks for feedback @blrhc, I will take it into account. I have three more sections to implement in the branding page, so that will probably take me today and tomorrow, then ~1 day for UI fixes, e.g. scaling on different screen sizes and 2 days for the assets page.

**Comment by blrhc** [comment]
> Thanks for feedback @blrhc, I will take it into account. I have three more sections to implement in the branding page, so that will probably take me today and tomorrow, then ~1 day for UI fixes, e.g. scaling on different screen sizes and 2 days for the assets page.

Thanks for the update sir!

**Pull request closed without merging**
