### PR TITLE
Fix Giza Launch Date

### PR DESCRIPTION
**Pull request by traumschule**
https://www.joystream.org/giza shows `launched`and links to 404 announcement post. This is confusing for new users.

### CODE REVIEW

**Comment by blrhc** [comment]
@DzhideX could you please merge this? (maybe into dev, not sure what the flow is now!)

**Comment by DzhideX** [comment]
@blrhc Hey, just been able to catch up to some of these tasks. Do we want to leave the new date as `01.02` or change it to the actual date it came out (as that has happened in the meanwhile)? We'd also want to change the data for `Road to mainnet` on the homepage as well.

**Comment by traumschule** [comment]
Updated the launch date again. The `Future Testnet` and `Current Testnet` labels need to be switched manually too?
> We'd also want to change the data for Road to mainnet on the homepage as well.

I can do it with bit input, is there a rough release date for olympia?

**Comment by DzhideX** [comment]
Yes, the `state` labels need to be updated and also the date as it is wrong here as well (you can find this under `src/data/pages/index.js`). Speaking of the date, isn't it [January 26th](https://blog.joystream.org/giza-released/)?

>I can do it with bit input, is there a rough release date for olympia?

Great idea for adding Olympia there. I think Feb 18th is the projected date (based on the previous community call) but we also need a new image and description text for that (@blrhc :eyes:).

**Comment by traumschule** [comment]
Updated labels, dates and added Olympia. Now it needs an image and a page too.

Did you think about adding navigation between releases to jump back and forth?

**Comment by DzhideX** [comment]
Oh I totally forgot we would also want that page to be done as well. I think it's best we scratch that idea for now as I'm not too certain we will be doing it soon and we'd want this fix out asap.

> Did you think about adding navigation between releases to jump back and forth?

I do think this is a cool idea but it's a bit out of context in this PR so maybe you can make an issue and tag Bedeho to see if he approves of it?

**Review by DzhideX — APPROVED** [review]
Great work!

**Pull request merged**
