### PR TITLE
Branding Pages

### PR DESCRIPTION
**Pull request by maciejmatu**
PR For branding pages

### CODE REVIEW

**Comment by blrhc** [comment]
Thanks @maciejmatu, will look at this too.

**Comment by blrhc** [comment]
Building now.

**Comment by blrhc** [comment]
@maciejmatu The main issue here is spelling vs any serious issue with the design. If you focus on #56 for now we can handle those minor issues later (as this page is not critical for branding rollout).

**Comment by blrhc** [comment]
Reviewing now, thanks again @maciejmatu!

**Comment by blrhc** [comment]
## Initial Review

### General Note
Obviously not your fault @maciejmatu as you didn't write it, but I have noticed that the text will need a lot of work in terms of fixing grammar, typos and evaluating the relevance and usefulness of what's written. I will work on improving the text and perhaps make some pull requests into your branches (if that's OK for you) and if I break anything just modify the PRs.

I think it was a good decision not to include these pages in the initial branding rollout as the text is clearly not ready yet.

### Guide Page (`brand/guides`)
Here are a couple of issues I noticed:
1) When the page is resized, some alignment issues occur:

guide_logoalignment

2) What is the purpose of this raw link?

guide_weirdlink

3) I like these sliders as a concept but I think they need to be so that the buttons are the same width as the photo gallery element.

guide_slider

guide_sliderwidth


4) In some cases, especially when the page is resized, the text is inappropriately sized (see "Horizontal Lockup").

guide_textsize

5) White space in footer when resized

guide_emptywhitespace

6) Image alignment issues

badalignment

7) Not sure of the purpose of this asset (is it supposed to be an animation?)

guideanimation


### Brand Story Page (`brand/story`)

As with the guide page, occasionally elements (e.g. buttons) are misaligned when the page is resized.

brand_alignment

### Assets Page (`brand/assets`)

I like that you have set this up to pull assets from the GitHub repo and the general design actually works very well. We will later on need to reconfigure this as we will be updating the structure of that repo significantly (https://github.com/Joystream/design/pull/21).

I don't really like this "dead" section here which doesn't obviously link to anything. Is there any other way this could be represented? It feels as if it should do something when clicked like the other sections.

assets_expecting link

### Summary

@maciejmatu, if you could take a look at how to deal with these issues in a general sense (i.e. not limited to the specific examples highlighted), that would be greatly appreciated! 

I think the templates you have made are very good and you have definitely been very faithful to the invision mockups, we just need to deal with some of these smaller issues. :)

**Comment by maciejmatu** [comment]
1. Added an additional breakpoint for logos safe use section. It should look better now. 
2. Added a description text to `duotone` link so it's purpose is clear
3. Updated slider bar size to be the same as single slide width
4. Made the `vertical/horizontal` lockup font size bigger on mobile
3. Fixed whitespace issue on the bottom of the page
4. Added missing margin to some images (bell image and one more I found)

6. Added dropdown to typography section, that downloads the same assets package as the main typography download button
7. Added video in motion section

**Comment by blrhc** [comment]
## Secondary Review

@maciejmatu You've done some good work here fixing some of the the issues I identified, I particularly like the solution to the font download link, it now feels much more intuitive. The animation on the `brand/guides` page also works well.

There are still some things which need to be dealt with across the three pages.

### Slider

I still think the slider could be improved. Might you perhaps try introducing a margin between the sliders and the right-hand side of the page (may require a slight redesign in the way they function) while also making the slider buttons the full width of the gallery?

### Text Sizes

In this most recent review, I've noticed that body text which in desktop view is all the same size is rendered as being multiple different font sizes once on a smaller screen. Some examples are below:

text size varies again
text size varies

### Inappropriate Spacing

There are quite a few areas where there are big spaces for no reason (especially when the pages are resized).

spacing

### Out-Of-Proportion Elements

Make sure elements don't look ridiculously large in comparison with the text (and vice versa).

outofproportion

### Inappropriate Alignment

In many cases, text and assets are aligned to the left by default but this is not work very well visually. Please try to address this issue where you identify it.

inappropriate left alignment


In answer to your final question, I think the buttons I highlighted in the last review should probably be centered or made the full width of the section.

**Comment by maciejmatu** [comment]
### 1. Slider 
I'm not sure what to do with the slider to be honest, but If you prefer for it to be the same width as the container, we can try something like that
image
This way it would always display only 2 slides, and would have the same width as the parent. As an alternative I can also hide overflow to the right and make it look like this:
image

### 2. Text Sizes
It should be fixed now. I added the correct scaling for tablet breakpoint there.

### 3. Inappropriate Spacing
Also unified the spacing a bit, so it should be smaller and more consistent. 

### 4. Out-Of-Proportion Elements
Not sure what could be a fix here. I could make the images smaller and center them? Do you have an idea how to tackle this?

### 5. Inappropriate Alignment
Centered the text in the specified screenshot, but I didn't find any more similar issues at this moment. If you have anything specific in mind just screenshot where it's an issue and I'll fix it 👍 

### 6. Button size
I made the button full width

**Comment by blrhc** [comment]
1) Yes, the first example looks good, could we try it like that?
2) Thanks, looks much better now!
3) Also seems better :)
4) I think just make sure to build the site every time and then view it in a reduced window size so you can judge what the relative sizes should be? 
5) Ok, I will keep looking for areas where this might be occurring.
6) Thanks!

**Comment by blrhc** [comment]
first slider

Hi, great work fixing those issues. One thing I have noticed is that on the new slider in the first example I could see the blue from the third slide when only two are supposed to be visible. This behaviour can be observed above.

**Comment by maciejmatu** [comment]
@blrhc nice catch! Pushed a fix for it :+1:

**Comment by blrhc** [comment]
i

Is there any chance you could add some HTML colour codes here to be consistent with the proceeding section? 

navigation
Also if you could make sure that all the titles of the sections are the same as they are written in this navigation section e.g. the section title should be `Patterns` as above not `Joystream Patterns`

**Pull request merged**
