### PR TITLE
Get started

### PR DESCRIPTION
**Pull request by DzhideX**
This is the first implementation of the `get-started` page. 

- There's still some animation and color changes necessary for the bounties carousel.
- The bounties are static for now.

Everything else should be done!

### CODE REVIEW

**Review by bwhm — CHANGES_REQUESTED** [review]
Two real issues only:

1. Bounties should from the json at location url [here](https://github.com/Joystream/community-repo/pull/90)
2. The Roles section is currently not working as intended, and some of the info is incorrect:
   - Available Roles: `Validator`,  `Council Member`, `Content Curator`, `Storage Provider`
   `Nominator` and `Content Creator` is a little bit of a stretch. @blrhc?
   - "Active roles on the current testnet" probably needs a lot of work, so lets make it simple for now. Either:
      - List all these roles, but remove "Participants" from all, and fetch the reward from tokenemics
      - As above, but scrap rewards as well...
      - Scrap the whole thing, and make the all the roles links to our helpdesk (correct roles)

**Comment by bwhm** [comment]
@DzhideX 
I should add that it would be nice to remove bounties from the current /testnet page in the same PR, since they'll go another place. They are currently read from the same json as the KPIs.

Perhaps @blrhc can help clean up that page at the same time? It needs to update some of the text, and perhaps instead link to the new get-started page (which I'm not sure is very accessible atm)?

**Comment by blrhc** [comment]
Suggestion on text for Roles section:

Screenshot 2021-02-16 at 15 10 27

This seems a bit broken if the bounty title is too long:

Screenshot 2021-02-16 at 15 06 40

Cleaned up the title bit, needs line break too between title and subtitle.
Screenshot 2021-02-16 at 15 05 40

**Comment by DzhideX** [comment]
I made the textual changes but have a couple comments/questions about the stylistic changes:

2. Initially I thought so too but I think it's weird-looking just because there's one item there. If you look closely, the whole right side is missing (to signify that it is scrollable?). The only fix here would be to make the width smaller which would mess with the available space even more.
3. Regarding the break here. Compared to previous heros where there was a massive amount of space between the title and subtitle, lately this has been changed in favor of this new style. This can be seen on FM as well as I remember Bedeho specifically telling me to use the new style. Photo from the design:

exampleHero

**Comment by bwhm** [comment]
> Initially I thought so too but I think it's weird-looking just because there's one item there. If you look closely, the whole right side is missing (to signify that it is scrollable?). The only fix here would be to make the width smaller which would mess with the available space even more.

It does look a bit weird now, but I'd rather tweak later. We need to deploy!

> Regarding the break here. Compared to previous heros where there was a massive amount of space between the title and subtitle, lately this has been changed in favor of this new style. This can be seen on FM as well as I remember Bedeho specifically telling me to use the new style. 

I don't understand exactly what you mean here.

If there is nothing outstanding at this point, I'd say we push this!

@blrhc ?

**Comment by DzhideX** [comment]
The only thing remaining at this point is for @blrhc to write the overviews for the active roles section.

After that, I can add the accompanying icons/images, get rid of rewards/participants and add the necessary links for the buttons.

**Comment by blrhc** [comment]
### Validator

A Validator is an actor which checks the validity of newly constructed blocks, proposes new blocks and participates in the consensus process for committing new block to the chain. Validators are typically paid a fixed amount for each block produced. This role has a purpose very similar to that of the miners in the Bitcoin blockchain.

### Council Member

Council Members are elected by stakeholders in the system to act in the long-term interest of the platform. They are responsible for allocating resources, and hiring working group leads to run the platform's day-to-day operations. This is done through the proposal system, allowing any user to submit suggestions for changing the platform in some way.

### Storage Provider

There are critical platform assets that do not live on the blockchain, such as content media. The integrity of these assets is secured by the chain, but a separate set of storage and distribution nodes enable uploading and downloading of such data. The Storage Provider is involved this activity, specifically by storing large quantities of data.

### Content Creator

Content Creators are those platform participants who have decided to contribute their own original (or third-party licensed) content to the platform. There are no direct incentives for this informal role at this time, though effective contributors are very likely to be rewarded through the Founding Member Program.

### Content Curator

Content Curators are responsible for monitoring the publishing of new content into the content directory, and responding to reports about contested publications. They must also update information on content to ensure it is accurate, with correct metadata. Collaborating with Builders to improve tools and user-facing experiences is another significant part of the role.

### Storage Lead

The Storage Lead is hired directly by the Council through the proposals system and is dedicated to the hiring, firing and wider management of Storage Providers on the network.

### Content Lead

The Council has the power to appoint a Content Curator Lead for the network who can hire further Content Curators. The Content Lead also decides on priorities for curation. If necessary, upon discussing with the council, the Lead can also decide to fire curators who are not performing their jobs adequately.

**Review by bwhm — APPROVED** [review]
Looks good to me!
Nice work :)

**Review by blrhc — APPROVED** [review]

**Pull request merged**
