### PR TITLE
Fix hamburger icon

### PR DESCRIPTION
**Pull request by kosorz**
This PR is related to [this](https://github.com/Joystream/joystream-org/issues/308) issue.

Fixing and enhancing menu hamburger icon.

image

### CODE REVIEW

**Comment by kosorz** [comment]
I've switched base branch, no problem on my end. However now it looks like I want to merge 11 commits. Is there any problem with that? :P

**Comment by blrhc** [comment]
@kosorz Ideally, it would be really excellent if you could make the changes on a sensibly named feature branch on your fork (based on our `development` branch) and then PR into development, but if that's not feasible then let me know and we can perhaps make an exception in this case.

**Comment by kosorz** [comment]
Sure @blrhc I will handle that in few hours but could you please consider adding some "How to contribute" guidelines within Readme for us the web wanderers? :)

**Comment by blrhc** [comment]
> Sure @blrhc I will handle that in few hours but could you please consider adding some "How to contribute" guidelines within Readme for us the web wanderers? :)

Definitely, will look into that for sure!

**Pull request closed without merging**
