### PR TITLE
Add joy price

### PR DESCRIPTION
**Pull request by DzhideX**
Implementation finalization for token page hero stats. Added token price and FDV calculation.

Also, previous PR was merged directly into master so I pulled upstream master into dev, ended up in a weird looking commit preview below but I think it ought to be fine.

### CODE REVIEW

**Comment by bedeho** [comment]
nice job!

could you perhaps make the FDV a bit more readable, using some sort of formatting thing to add commas and so on. Same with supply

**Comment by DzhideX** [comment]
I added some formatting to the FDV and supply. The value ended up being a bit too large for the container so I had to adjust the padding, let me know if it looks good!

**Comment by bedeho** [comment]
Hey, why does the commit history look so funky? Also, would you dare update this section and add MEXC logo with link? This is a slightly design intensive task, but lets see if you can do it :)

Screenshot 2023-06-23 at 18 59 28

**Comment by DzhideX** [comment]
> Hey, why does the commit history look so funky?

I mentioned above: "Also, previous PR was merged directly into master so I pulled upstream master into dev, ended up in a weird looking commit preview below but I think it ought to be fine." It might be that I did something wrong but the changes look to be correct so I think it should work out in the end 😄 

> Also, would you dare update this section and add MEXC logo with link? This is a slightly design intensive task, but lets see if you can do it :)

The designs included a "No exchanges" variant along with one with exchanges. I went ahead and implemented it according to those designs, let me know if it looks good!

P.S. I also added the token stats section to the landing page on this PR, let me know what you think about that as well!

**Comment by bedeho** [comment]
Excellent job, this is great. I would lastly ask

1. Update "supply" to "total supply" on both landing page and token page
2. Add a header for the token metrics section on the landing page, so I am referring to adding something like 
Screenshot 2023-06-25 at 22 14 07

Where we do
"ECOSYSTEM" => "TOKENOMICS"
"One platform. Multiple apps." => "Key Metrics"

try to manage the different vertical margins so it does not get too large or too small.

**Pull request merged**
