### PR TITLE
lightpaper from v1.1 to v1.2

### PR DESCRIPTION
**Pull request by DzhideX**

### CODE REVIEW

**Comment by bedeho** [comment]
Filename still has to be lightpaper.pdf, as many links are anchored to this.

**Comment by DzhideX** [comment]
Whoops, seems to have pushed v1.1 again. Fixing!

**Comment by DzhideX** [comment]
Actually no because locally the version is 1.2 and in the commit, the 1.2 version was correctly pushed: https://github.com/Joystream/joystream-org/blob/d9a2c8c0682958c65b5660578f5a8279b1d666b5/public/lightpaper.pdf

Vercel seems to be bugging out as both `lightpaper.pdf` and `lightpaper_v1.2.pdf` are accessible on that URL: [v1.1](https://joystream-lpdo0tuwm-joystream.vercel.app/lightpaper_v1.2.pdf), [v1.2](https://joystream-lpdo0tuwm-joystream.vercel.app/lightpaper_v1.2.pdf)

**Comment by bwhm** [comment]
@DzhideX 
I forgot about this one. Let's try to merge to master and if the issue persists, I'll wipe the cache...

**Comment by bwhm** [comment]
> Actually no because locally the version is 1.2 and in the commit, the 1.2 version was correctly pushed: https://github.com/Joystream/joystream-org/blob/d9a2c8c0682958c65b5660578f5a8279b1d666b5/public/lightpaper.pdf
> 
> Vercel seems to be bugging out as both `lightpaper.pdf` and `lightpaper_v1.2.pdf` are accessible on that URL: [v1.1](https://joystream-lpdo0tuwm-joystream.vercel.app/lightpaper.pdf), [v1.2](https://joystream-lpdo0tuwm-joystream.vercel.app/lightpaper_v1.2.pdf) (should not be possible..)


After merging to development, I "still" downloaded v1.1 but the equivalent second link didn't work.


I then did a manual redeploy in vercel, disabling the build cache, and https://joystream-org-git-development-joystream.vercel.app/lightpaper.pdf -> v1.2

**Pull request merged**
