### PR TITLE
update cookie banner

### PR DESCRIPTION
**Pull request by kdembler**
Closes https://github.com/Joystream/marketing/issues/277

@toiletgranny I think we need some improvements for the mobile version, could you prepare something in Figma?

### CODE REVIEW

**Comment by toiletgranny** [comment]
@kdembler I also couldn't get the cookies banner to show up.

**Comment by kdembler** [comment]
@dmtrjsg @toiletgranny Yep sorry, there was a bug. It should work now.

@dmtrjsg I wasn't able to reproduce the issue you've mentioned, is this still happening for you? If yes, could you provide some additional details on the browser version?

**Comment by dmtrjsg** [comment]
@kdembler Safari Version 15.3 (17612.4.9.1.5)

**Comment by toiletgranny** [comment]
Looks great! I appreciate the additional transition animation!

1. May I suggest applying `536px` of `max-width` on the cookie message, instead of using the `<br>` tag to break the text? This way the text looks better on mobile.
2. With the cookie banner opened I can see a little bit of white space on the right. Is there an easy fix for this?
https://user-images.githubusercontent.com/35307309/183905308-3c438302-e1f6-42da-9940-dc41a7764890.mp4

Except for the above, this is good to go to me! ❤️

**Comment by kdembler** [comment]
1. Is more elegant indeed, updated
2. This actually isn't introduced by my PR, it was there before. But fixed nonetheless

**Pull request merged**
