### PR TITLE
Create/roadmap page

### PR DESCRIPTION
**Pull request by HeinrichOlfert**
This is for roadmap page described in https://github.com/Joystream/joystream-org/issues/644, https://github.com/Joystream/joystream-org/issues/661

### CODE REVIEW

**Comment by DzhideX** [comment]
Great first steps. There's more work before we can finalize that first deliverable but it's starting to shape up quite nicely :)

To start off the review, I think there was a bit of a misunderstanding. I didn't want you to remove prettier but rather uncommit the files with only prettier changes. Prettier changes are fine but keep them only within the files you've changed, not all files in the codebase.

So, before I can do a proper review please uncommit those unnecessary files. Also, let's keep all the changes in one PR, no need to open a new PR every time you need to change anything.

I didn't look too much at the code but here are some thoughts from a general design/implementation POV:
- For the data itself, we want both 2023 and 2024 to be on the roadmap at the same time. If you did this to show the picker functionality then just use the same data for both versions for now.
- The animation for the roadmap is yet to be implemented.
- Missing warning banner when not previewing the newest roadmap. 
- Missing hover on roadmap item link items.
- Missing ability to copy roadmap item links. When opened they should scroll/animate to that item.
- Missing disclaimer banner.
- Missing or wrong margins (examples: first roadmap item should be 96px away from the elements above, it's only 20px in the implementation; there are missing margins between items in roadmap items)

For the designs, make sure to follow everything in the designs as much as possible. We're going for a 100% identical implementation. I don't know if you've missed it but there's also a brilliant video that you should watch made by the designer to explain the designs and animations: https://www.loom.com/share/0a21ed664b4840e7953c94277ed40fa5?sid=959cafb9-9ef1-4c07-9202-62487d05a66e

**Comment by DzhideX** [comment]
This latest version looks great but we definitely want to pay more attention to detail as some obvious things are still not implemented quite right. There are also things that I mentioned in the previous review that were potentially ignored/not implemented this time around either.

Things to fix:
- For the data itself, we want both 2023 and 2024 to be on the roadmap at the same time. If you did this to show the picker functionality then just use the same data for both versions for now.
- The background design on the hero section isn't aligned quite perfectly. Can we take another look into that?
- The roadmap section title should be capitalized.
- The margin between the roadmap picker and subtitle is wrong.
- The roadmap item and link icons are not quite right. The main roadmap item icon might need to somehow be integrated into the data model as it changes for different types of content.
- Roadmap item content margins wrong.
- The space around the scrolling dot (the one showing the current position) is not quite right. In the design, it's 76px + 60px (margins) whereas in the implementation it's 149px together.
- Missing "More plans will be announced over time." roadmap item as an option. That is, a generic item with no icons.
- The animation (although essentially almost done) is not quite right still. More specifically:
  - In some instances, the gray circle disappears after moving past it. This shouldn't happen.
  - Sometimes it snaps into place but it shouldn't.
  - The text should overlap when moving between one quarter into another.
  - There should be dots next to each item and at the end as well.
  - You can take a look at the example animation here: https://github.com/Joystream/atlas-resources/blob/main/video-files/Roadmap_scrolling_animation.mp4
- Disclaimer shouldn't have a close button. I believe it's permanently there.
- Change to the current version link doesn't work in the information banner (when not previewing the latest version).
- The style for the "close" icon on the same banner isn't quite right.
- The general functionality around different versions of roadmaps and linking to them is a bit buggy. Examples:
  - When clicking on the first choice in the picker on the initial load I get the following URL: https://joystream-cd0678jqs-joystream.vercel.app/roadmap/#undefined
  - Clicking on one of the links in such a state doesn't allow me to go to it properly.
  - Also, occasionally the animation of these items is a bit buggy.

I think it makes sense to focus on completing the roadmap section properly before we move on to the rest which is why I only focused on that in the review.

**Comment by KubaMikolajczyk** [comment]
@DzhideX  - Wow what a phenomenal implementation of the designs ❤️ I love how you handled the animation of changing the active roadmap step - Its flawless ⭐️ also I think find the glossary working really good! Thank you for that. I found just a few minor issues that I want to outline here:

# 1. Page loading
image
It happens often when I start loading the page that I don't have any roadmap elements - and I understand that it happens because of the fact that we have to pull the data for those roadmap elements. Could we however use the loader state of the roadmap card components and just load them as we get the data? Look like this one for example - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12250&mode=design&t=kFVbFWiaxnsgiMtg-4)

 It would be much easier on the eyes and could avoid some confusion - If we could have some placeholders as we load.
 
 # 2. Components
 
image
 - Added hover state for select component - which you can find here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3936&mode=design&t=kFVbFWiaxnsgiMtg-4)
 
 
image
 - The select dropdown has a big gap between itself and the select - it should have no gap + the dropdown itself should be built a bit different its lacking 8px padding on top and bottom - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12246&mode=design&t=kFVbFWiaxnsgiMtg-4)
 
 
image
 - When I click on the copy link icon button inside of the roadmap goal card - I don't see hand coursor, when clicked the state shows two msgs about copying to clipboard one after another and it stays in a pressed state even when its not pressed anymore
 
 
image
 - External link element in text should be a clickable link 

image
- We are missing a hover effect on those cards - you can find them here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3913&mode=design&t=kFVbFWiaxnsgiMtg-4)
 
 
image
image
- The selected, with some input inside, searchbar is lacking some styling should be 2px border with 2px border radius
- The close icon button inside should be an icon button instead of just icon - it has a hover and press effects, and should be positioned differently look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-11217&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
image
- The same goes for the icon button inside of this banner, also should be a button with icon inside not just the icon alone with hover and press states, see here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12254&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
image
- It looks like there is some issue with positioning of the icon inside of the banner here - its not aligned as it should be look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12254&mode=design&t=kFVbFWiaxnsgiMtg-4) and [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-2889&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
image
image
The icon holders should be 48x48 not 40x40 and the icons inside of the holders should be 24x24 - look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3984&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
- We are missing three dots at the end of the sentence that was shortened here to fit in tooltip

image
This shouldn't be displayed if we have only 4 terms as nothing happens when clicked - should be displayed when we have 5 or more

image
The grid here should have 30 gap - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=360-42389&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
image
Letter filter should have 8px of space between each other

# 3. Mobile

image
Version selector only works when you click on certain areas, like around the edges or on the text , but clicking in the middle or on the chevron does not trigger a dropdown

image
Tooltip also should be spaced with 16 px of margin in mind

image
- Small variant of banner does not fill 100% of the container
- In this variant the icon is also not aligned + we need an icon button for close action too
image
The gap between the title and text should be equal to 8px not 16, same goes for gap between text and the text button

image
The roadmap goal cards are positioned in such way that there is no margin on the right side but there is a huge gap between card and the track of the "slider" - look how mobile view should look like - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3511&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
Here the icon is aligned badly and the large wrapper on it makes the top padding look too big

image
The searchbar does not fill the container and sticks out of the screen 

image
The space between cards on mobile should be 16 px - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3600&mode=design&t=kFVbFWiaxnsgiMtg-4)

# 4. RWD
Lets set up a call to discuss the RWD I can see we can improve it but it will be easier to do it together.

# 5. Glossary terms

image
We are missing padding bottom 16px on paragraphs

image
The link styling should be different - [link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3123&mode=design&t=kFVbFWiaxnsgiMtg-4)

image
We lack the hover effect for a roadmap link see how it should look like - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12558&mode=design&t=kFVbFWiaxnsgiMtg-4)

**Comment by HeinrichOlfert** [comment]
> @DzhideX - Wow what a phenomenal implementation of the designs ❤️ I love how you handled the animation of changing the active roadmap step - Its flawless ⭐️ also I think find the glossary working really good! Thank you for that. I found just a few minor issues that I want to outline here:
> 
> # 1. Page loading
> image It happens often when I start loading the page that I don't have any roadmap elements - and I understand that it happens because of the fact that we have to pull the data for those roadmap elements. Could we however use the loader state of the roadmap card components and just load them as we get the data? Look like this one for example - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12250&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> It would be much easier on the eyes and could avoid some confusion - If we could have some placeholders as we load.
> 
> # 2. Components
> image
> 
> * Added hover state for select component - which you can find here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3936&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image
> 
> * The select dropdown has a big gap between itself and the select - it should have no gap + the dropdown itself should be built a bit different its lacking 8px padding on top and bottom - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12246&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image
> 
> * When I click on the copy link icon button inside of the roadmap goal card - I don't see hand coursor, when clicked the state shows two msgs about copying to clipboard one after another and it stays in a pressed state even when its not pressed anymore
> 
> image
> 
> * External link element in text should be a clickable link
> 
> image
> 
> * We are missing a hover effect on those cards - you can find them here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3913&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image image
> 
> * The selected, with some input inside, searchbar is lacking some styling should be 2px border with 2px border radius
> * The close icon button inside should be an icon button instead of just icon - it has a hover and press effects, and should be positioned differently look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-11217&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image image
> 
> * The same goes for the icon button inside of this banner, also should be a button with icon inside not just the icon alone with hover and press states, see here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12254&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image image
> 
> * It looks like there is some issue with positioning of the icon inside of the banner here - its not aligned as it should be look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12254&mode=design&t=kFVbFWiaxnsgiMtg-4) and [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-2889&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image image image The icon holders should be 48x48 not 40x40 and the icons inside of the holders should be 24x24 - look here - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3984&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image
> 
> * We are missing three dots at the end of the sentence that was shortened here to fit in tooltip
> 
> image This shouldn't be displayed if we have only 4 terms as nothing happens when clicked - should be displayed when we have 5 or more
> 
> image The grid here should have 30 gap - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=360-42389&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image image Letter filter should have 8px of space between each other
> 
> # 3. Mobile
> image Version selector only works when you click on certain areas, like around the edges or on the text , but clicking in the middle or on the chevron does not trigger a dropdown
> 
> image Tooltip also should be spaced with 16 px of margin in mind
> 
> image
> 
> * Small variant of banner does not fill 100% of the container
> * In this variant the icon is also not aligned + we need an icon button for close action too
>   image
>   The gap between the title and text should be equal to 8px not 16, same goes for gap between text and the text button
> 
> image The roadmap goal cards are positioned in such way that there is no margin on the right side but there is a huge gap between card and the track of the "slider" - look how mobile view should look like - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3511&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image Here the icon is aligned badly and the large wrapper on it makes the top padding look too big
> 
> image The searchbar does not fill the container and sticks out of the screen
> 
> image The space between cards on mobile should be 16 px - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3600&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> # 4. RWD
> Lets set up a call to discuss the RWD I can see we can improve it but it will be easier to do it together.
> 
> # 5. Glossary terms
> image We are missing padding bottom 16px on paragraphs
> 
> image The link styling should be different - [link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3123&mode=design&t=kFVbFWiaxnsgiMtg-4)
> 
> image We lack the hover effect for a roadmap link see how it should look like - [Link](https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-12558&mode=design&t=kFVbFWiaxnsgiMtg-4)

**1. Page loading**
Added loader state

**2. Components**
- the hover state is the same as default state for the dropdown list component in the figma
https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=1-3936&mode=design&t=XqnMZqFNXZ2tgvPA-0
- eliminated gap between dropdown and list items
- added hand cursor to all links and fixed active state
- **where does {external link} lead to?**
- added hover effect to cards
- fixed selected state of searchbar
- fixed close icon button for searchbar and banner
- fixed positioning of icons
- fixed size of icon holder
- added three dots to tooltips
- remove "show..." for less than 5 items
- 30px gap to grid, 8px gap to alphabet

**3. Mobile**
- version selector fixed
-

**Comment by bedeho** [comment]
This looks like a bug

Screenshot 2023-10-04 at 13 15 47

**Comment by bedeho** [comment]
I see no Roadmap in menu?

**Comment by KubaMikolajczyk** [comment]
1. RWD single term page
image
Can we use the same RWD rules for the body as we use for the top nav?

2. Loading of roadmap 
image
- Why do we display "Version 6" in select?
- Why do we display the banner when loading about old roadmap version?
- can we display more than one empty item when loading - is there any way to know how many roadmap items we have before loading all of the content? Maybe we could use this number?

3. The hover/press state is not the same as default for the select in designs: Please interact with this prototype of select - [Link](https://www.figma.com/proto/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?page-id=1%3A2&type=design&node-id=485-4620&viewport=-1817%2C5454%2C0.99&t=7iomwvSgNdiFhiFT-1&scaling=min-zoom&starting-point-node-id=1%3A2829&mode=design)

4. RWD of Roadmap goal cards still can be improved - there is a lot of unused space in the small screens sizes
image

5. This space here - why its here?
image

6. RWD of disclaimer also can be improve it looks like keeping those fixed and not using a grid system on RWD leads to a lot of unnecessary space + there is a white space under the disclaimer itself 
image

7. Both close icon buttons are using too big icons inside 
image
image
Please compare it to designs below
image
image

**Comment by KubaMikolajczyk** [comment]
@DzhideX @HeinrichOlfert reviewed the current implementation and there is still room for improvement + found new issues that were not here before. Everything can be found in my review in figma: https://www.figma.com/file/Q4mBIcKaFr8aUyv2ZWAXJY/Roadmap?type=design&node-id=524-38530&mode=design&t=xSBG85LILAWiN843-4

**Comment by HeinrichOlfert** [comment]
i have updated as requested

**Comment by bedeho** [comment]
I entered this site, and it took 3s to see broken UI, I'm astonished at the pace of this work.

Look at this

Screenshot 2023-10-13 at 12 09 04

There is a weird artefact here, and no line....?

I'm using Firefox 118.1

**Comment by HeinrichOlfert** [comment]
> I entered this site, and it took 3s to see broken UI, I'm astonished at the pace of this work.
> 
> Look at this
> 
> Screenshot 2023-10-13 at 12 09 04
> 
> There is a weird artefact here, and no line....?
> 
> I'm using Firefox 118.1

I've fixed that minor problem. I think this has never been tested on firefox. I quickly skimmed in firefox and saw nomore unexpected errors.

**Pull request merged**
