### PR TITLE
Verification page

### PR DESCRIPTION
**Pull request by DzhideX**
Implements verification page detailed in the following gist: https://gist.github.com/bedeho/1aabde02952b0036746f347d1002b209

Page can be found under the following route: `/freakstatic`

Questions/notes:
- What functionality should the report button have? Apparently some google form?
- Is it ok to use this telegram/email icon that we already had or should I change?
- Current verified data is temporary, do we already have in mind who we want to place in there? Preferably at least 2 people such that the last component makes any sense.

### CODE REVIEW

**Comment by KubaMikolajczyk** [comment]
@DzhideX Thank you for this - its awesome to see it in implementation 🙇 Great job - the animations looks really nice :)
I found some elements that still need a little improvement:

1. We dont use the PX Grotesk font at all on this page - IBM Plex sans for most headers & Inter for most body.

2. The title & subtitle should be center aligned with the avatar image like in designs. In implementation its not aligned.
image

3. In other team members section in the visible 2 row grid we have a big gap at the end - looks like the lest pill is not appearing here where it could fill the empty space
image

4. Additionally the button "show x more members" is a tertiary button from the web components librery and should have the hover and pressed state

5. Lastly when section is expanded the other "member" pills have no image inside

**Comment by bedeho** [comment]
Can I ask for definitive schema of what input is required per person to comply with this page?

**Comment by KubaMikolajczyk** [comment]
6. The RWD needs a little bit of more work - currently in implementation we have a layout with fixed width container that changes the fixed width on 1 breakpoint - while in designs the RWD describes the width of the containers based on column grid system on small screens should use all 12 columns and with only 6 central columns used for the layout on large screens.
image

**Comment by DzhideX** [comment]
@KubaMikolajczyk Thank you for the review, I'll fix those asap!

@bedeho Here's an example object that can be used for each person's verification page (this one's from the freakstatic page):
```
  {
    memberHandle: 'freakstatic',
    avatarUrl: 'https://raw.githubusercontent.com/Joystream/founding-members/main/avatars/primary-avatar/3.png',
    title: 'verification.title.userAcquirer',
    socials: {
      telegram: '@freakstat_ic',
      twitter: '@freak_static',
      email: 'freak.staticaly@gmail.com',
      discord: '@freakstatic',
    },
    safety: {
      notAllowed: [
        'verification.safety.willNever.items.askForMoney',
        'verification.safety.willNever.items.askForPersonalInformation',
        'verification.safety.willNever.items.sendAnythingDangerous',
      ],
      allowed: [
        'verification.safety.can.items.invite',
        'verification.safety.can.items.answerQuestions',
        'verification.safety.can.items.getFeedback',
      ],
    },
  },
  ```

**Comment by DzhideX** [comment]
Hi @KubaMikolajczyk , I was able to tackle all of the problems you mentioned in your review but I have questions about number 6.

Earlier when implementing RWD as you documented I had some problems with UI not working (this could be a result of my misunderstanding of your RWD system but we'll get to that). Namely, when I try to follow the designs I have the following happen between the ~500px and 425px breakpoints:

Screenshot 2023-09-02 at 04 00 04

Now, this is without word wrap but I think the point still stands (as there is so little space left on the card). This wasn't my only reservation but as hinted earlier there might be a lack of understanding with how I'm expected to go about implementing this. When looking at the designs, I just look at the breakpoints and implement them based on width, the different padding, font sizes, etc., but I wasn't sure what you meant with the different columns. Would you mind explaining or be able to point me to a resource where I'd be able to learn about this?

**Comment by DzhideX** [comment]
With the previous commit, expanded pages to implement 2 new entrants. Relevant issue: https://github.com/Joystream/joystream-org/issues/698

**Review by bedeho — APPROVED** [review]

**Pull request merged**
