### PR TITLE
Community page

### PR DESCRIPTION
**Pull request by DzhideX**
This PR implements the Community page detailed in this issue: https://github.com/Joystream/joystream-org/issues/575

Note:
- The implementation is missing the URL for the link to Element. I assume Dmitry might know what link needs to go there?

cc @dmtrjsg @toiletgranny

### CODE REVIEW

**Comment by toiletgranny** [comment]
Looks great! It seems like each card has a fixed height value, causing them to be shorter than they should be on the smaller screen size. Other than this, 👌!

I think that a link to that page should be in the footer, probably in the _Useful links_ column, at the top.

**Comment by DzhideX** [comment]
> Looks great! It seems like each card has a fixed height value, causing them to be shorter than they should be on the smaller screen size. Other than this, ok_hand!

Thank you! As for the card dimensions, are they not different on mobile? Specifically, they're `288x164px` in the desktop variant and `335x156px` in the mobile variant from what I can tell. Maybe I'm not understanding your point?

**Comment by toiletgranny** [comment]
@DzhideX You're right, the final height is the same, but if you disable the `height` property in DevTools you'll notice that, on mobile, the card becomes taller. Only now I realized why was that: it's the icon wrapper that has both `48px` of width and height on mobile, whereas it should be `40px`.

**Comment by dmtrjsg** [comment]
@DzhideX Here's the url for element: https://app.element.io/#/room/#js-general:matrix.org

**Pull request merged**
