### PR TITLE
Implement changenow section

### PR DESCRIPTION
**Pull request by DzhideX**
This PR aims to implement the changenow section outlined here: https://github.com/Joystream/joystream-org/issues/794

Note:
- As the iframe doesn't support a width greater than 640px and a height greater than 356px I have taken some creative liberties in adjusting the design to accommodate that.

### CODE REVIEW

**Comment by bedeho** [comment]
Does this use the API key for Jsgenesis?

**Comment by bedeho** [comment]
We def. need a way to link explicitly to this section, is that possible?

**Comment by DzhideX** [comment]
> Does this use the API key for Jsgenesis?

I believe so. The code snippet for the widget was given to me by @WRadoslaw. It uses the following id (which I think is the relevant part): `link_id=836b188968aaa`.

> We def. need a way to link explicitly to this section, is that possible?

Certainly! At the moment to link to this section we append `#instantSwap` to the URL of the token page. Let me know if we want to change that value to something else! Right now it looks like this: https://joystream-org-git-fork-dzhidex-implement-changenow-joystream.vercel.app/token#instantSwap

**Comment by bedeho** [comment]
> Certainly! At the moment to link to this section we append #instantSwap to the URL of the token page. Let me know if we want to change that value to something else! Right now it looks like this: https://joystream-org-git-fork-dzhidex-implement-changenow-joystream.vercel.app/token#instantSwap

Ok great, but can we add like a button or something, which allows someone to copy a link to the section? I know the people manning our chats and so on would have an easier time providing assistance to people with that.

**Comment by DzhideX** [comment]
We could add a button or similar, but I have some reservations with regards to it. The id approach is also used for other sections on the page without issues and they also don't have any buttons for this (examples: `token#exchanges`, `token#earn`). I just fail to see what problem we're trying to solve with this approach 🤔 

If you still want to go for it then I'll add it 👍

**Comment by bedeho** [comment]
ok, but how will people keep track of and learn waht the links are for each section?

**Comment by DzhideX** [comment]
Up until now, it's only been a handful of people that have needed it (tomato, Dmitry, HR workers), and usually, if they needed a link to a section they'd ask if there is one, if not I created them. This approach is also the standard way to link to different parts of pages across the web so I don't think people would be unfamiliar with it either (example: https://en.wikipedia.org/wiki/Blockchain#Blocks).

**Pull request merged**
