### PR TITLE
Founding members page

### PR DESCRIPTION
**Pull request by DzhideX**
This is the implementation of the second task from Issue: https://github.com/Joystream/joystream-org/issues/226

There are some things I would wish to note both from a visual and technical standpoint and my reasoning for the implementation:

- [Visual] The hero component (the one at the top) is not "identical" to the one in figma. The reasoning is that there already was a component created before which I reused.  Now, I didn't want to rewrite identical/similar code but if it isn't good enough the way that it is, I'll make it from scratch.

- [Visual] This one is very similar. In the current scoring period, I reused a counter component that already exists. It is very similar but not quite "identical" to the one in figma.

- [Technical] I'm planning on redoing the table code completely as I feel like I took the wrong approach and now the code is unnecessarily complex. It's fine for now but I think it would be perfect to update it during my next task which is the "Leaderboards tab".

- [Technical/Visual] Lastly, I didn't add the dropdown menu on the navbar yet as the code written for that would need to be updated heavily and I'd rather leave it for later as this is already a very big PR in itself. There is also no need for it yet.

One more small thing. I'm not sure if the button hovers are okay. I tried to go off of previous implementations.

### CODE REVIEW

**Comment by bedeho** [comment]
@mnaamani need Netlify integration to see this :)

**Comment by mnaamani** [comment]
> @mnaamani need Netlify integration to see this :)

I've already added the integration, however since I did that after the PR was created it is not automatically triggered. I don't see a way to trigger it manually, so the PR needs to be updated by pushing a commit.

**Review by bedeho — CHANGES_REQUESTED** [review]
First off, great initial work, looks very good. I will not review any implementation details, just UI. Also, thanks for the contextual explanation, that helps me understand yout thinking.

1. Thanks for the explanation of the header section, but I think we want to stay as true to the design as possible.

2. On the "current scoring period", again, lets stay true to the new design, and not reuse anything. There are also some issues, like the incomplete state of the progress bar not having any light background color

Screenshot 2021-01-05 at 17 57 09

, or the way the period number title looks in the top right corner.

Screenshot 2021-01-05 at 17 57 12


3. The "list of current foundign members" appears to have incorrect alignment when viewport width increases.

Screenshot 2021-01-05 at 14 51 52

4. the footer is not accurate

Screenshot 2021-01-05 at 14 52 27

5. Remove Canadian flag from ban list.

**Comment by bedeho** [comment]
Only thing is this bottom margin which was too small in mobile view

Screenshot 2021-01-14 at 12 43 23

Also occured to me that the footer is not different on this one page, from every other page. I think that needs to be consistent across all of them, so could you open a new PR which updates the footer to be like this on all other pages, and have it target the same branch `new_founding_members_ page`? I think we will just put a bunch of stuff in that branch, not just founding member stuff realistically.

**Pull request merged**
