### PR TITLE
New Landing Page Implementation

### PR DESCRIPTION
**Pull request by DzhideX**
This PR aims to implement the changed design for the landing page along with the changes explained in this issue here https://github.com/Joystream/marketing/issues/303.

One thing to note, I am aware of the bug where if you snap from one side of the animation to another the hero animation isn't being updated correctly. I'll look into why that is happening asap!

Edit: It seems that on the live version there are problems that can arise due to images loading while the animation is going (animation looks twitchy). Works fine after they are cached but definitely not optimal. Might need to look into pre-loading all of them on page load.

### CODE REVIEW

**Comment by dmtrjsg** [comment]
Good stuff mate, almost there.

1. CTAs should be View Apps and start community [pls check here> ](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=6923%3A383359&t=9HiwPzOhSgdbzu3l-1)
2. View Apps also should be the one in the top Nav 
Screenshot 2022-11-29 at 14 34 07
3. Link from Gleev Visit should point to > https://gleev.xyz
4. The animation does not scroll for me well skipping the stages but I'll leave it for @toiletgranny to provide a detailed targeted feedback on the desired mechanics.

**Comment by toiletgranny** [comment]
A massive PR. I genuinely admire the attention to detail, just like the last time. The new carousels, new illustrations, new sections, everything is just 😙🤌. The hero illustration was tricky from the start, but it already looks very promising. I especially admire the mobile implementation. 

Here are a few findings and suggestions from me:

1. **As is:** It seems half of the hero illustration animation is controlled, quite literally, by the scroll position (e.g., the image sequence), whereas the other half is only _triggered_ by reaching a certain scroll threshold, but the animation itself is played out with a predefined timing and easing (e.g., the way we go into different layers of the hero illustration). This execution is nice because it makes certain parts of the animation buttery-smooth and very satisfying to watch, but it also comes with a significant drawback: in order for this to work, the page needs to be scrolled at a very specific speed. Otherwise, the animation breaks, and we start to see glitches. And if you're unaware of this, it's very easy for you to spoil the fun by just scrolling too fast, which I can imagine will happen to a majority of first-time visitors. 

    https://user-images.githubusercontent.com/35307309/204490328-fe3bc1a8-4431-48d4-a14d-f413a2f1f90a.mp4
   
    **~~To be~~ Could be (?):** If the _entire_ hero illustration animation is controlled by the scroll position in the same manner as the image sequence currently is, then the outcome could be easier to control by the end user, and therefore less prone to be broken. This is, in fact, how our benchmark, the Apple Watch Ultra illustration, has been implemented. Here's my miserable attempt at visualizing what I have in mind: https://adams-trendy-site-6f826a.webflow.io/

2. **As is:** The hero illustration took a significant while to load on my end, but my understanding is that the compression/optimization exercises are still ahead of us. 
    **To be:** Let me know if you need any help in compressing the PNG images or converting them to another format. Also, an easy way to cut down on file sizes would be to cut the number of frames in half, dropping every 2nd frame.
3. **As is:** In step cards in the "How about starting your own video community?" section, it seems like "Step 1", "Step 2", etc. headers are rendered using wrong text style.
   **To be:** Step headers should be of `12 px` font-size, `16 px` line-height, and `0.25 px` letter-spacing.
4. **As is:** Links in the main navigation and CTA buttons haven't been changed.
    **To be:** This should be changed to reflect the designs.

**Comment by DzhideX** [comment]
Awesome! Thank you both for the review :heart: 

>CTAs should be View Apps and start community [pls check here>](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=6923%3A383359&t=9HiwPzOhSgdbzu3l-1)
View Apps also should be the one in the top Nav
>As is: Links in the main navigation and CTA buttons haven't been changed.

Indeed :man_facepalming: , I left the first part of the website for later and didn't write it down and of course forgot about it. Will fix that!

>  Link from Gleev Visit should point to > https://gleev.xyz 4

:+1:

> As is: It seems half of the hero illustration animation is controlled..

Yup.. Was probably my bias that I just didn't want to scroll faster even though I knew it would break and it is a fact of life that people usually just scroll very fast lol. My fear with making the middle part dependant on scroll was because of the way it is rendered. If you stop in the middle of it, it would be in some weird in-between state. That being said, the current approach just doesn't really work honestly.. I have to agree here that implementing it just like the other 2 parts just makes sense :100: 

> As is: The hero illustration took a significant while to load on my end

For this, I initially took the @2x frames but those were super intense performance-wise. As it currently stands I'm using a lossless compressed png -> webp (used this to convert: https://developers.google.com/speed/webp/docs/cwebp) of the @1x variants and that from what I could tell resulted in a ~30% reduction across the line. You'd say you'd go further by compressing the images even more? (I know you were very adamant about using @2x if possible)

I'll also try and experiment with removing frames and see how that goes..

> As is: In step cards in the "How about starting your own video community?" section, it seems like "Step 1", "Step 2", etc. headers are rendered using wrong text style.

:+1:

**Comment by toiletgranny** [comment]
> Yup.. Was probably my bias that I just didn't want to scroll faster even though I knew it would break and it is a fact of life that people usually just scroll very fast lol. My fear with making the middle part dependant on scroll was because of the way it is rendered. If you stop in the middle of it, it would be in some weird in-between state. That being said, the current approach just doesn't really work honestly.. I have to agree here that implementing it just like the other 2 parts just makes sense 💯

❤️❤️❤️



> For this, I initially took the @2x frames but those were super intense performance-wise. As it currently stands I'm using a lossless compressed png -> webp (used this to convert: https://developers.google.com/speed/webp/docs/cwebp) of the @1x variants and that from what I could tell resulted in a ~30% reduction across the line. You'd say you'd go further by compressing the images even more? (I know you were very adamant about using @2x if possible)

Interesting! When I right-clicked to download random frames from the implemented @1x animation sequence I got PNG files that were ~400 KB on average (400 KB * 91 frames = 36 MB), so there might be something wrong with the compression settings. For example, when I downloaded the very first frame, the file size was 558 KB, whereas the original PNG file is actually 498 KB. 

I don't know how to use the converter you linked (🙈), but when I passed the first frame through cloudconvert.com, I got a 25 KB @1x image (2.8 MB for all 91 frames, which I guess is very nice) and 76 KB @2x image (6.9 MB for all 91 frames), with the WEBP compression level set to 85 and the "Strip" setting to Yes. 

So, to answer the question: yes, I believe, we should convert the images further, both for @1x and @2x resolutions (for the @2x perhaps we could use even stronger compression settings).

**Comment by DzhideX** [comment]
> I can def. see that images are now compressed a bit more, but they also load much faster, so, to me, it's a huge win!

Awesome!

> However, with the new image compression, I feel like we lost the @2x scale image sequence on retina screens. Is this possible? If so, can we serve @2x images for retina screens?

We can definitely try. Since I'm rendering these images on a canvas I'm not sure how I'd go around doing it but I'll see if it's possible :+1:

> ... Let me know if you'd prefer a call to discuss this; I can do this first thing in the morning.

Yeah, I think it make the most sense to jump on a call and go through both of your points in more detail tomorrow!

**Comment by DzhideX** [comment]
These 2 issues should now be implemented as well: https://github.com/Joystream/marketing/issues/312 https://github.com/Joystream/marketing/issues/314

**Pull request merged**
