### PR TITLE
Update joystream/types for Giza

### PR DESCRIPTION
**Pull request by freakstatic**

### CODE REVIEW

**Comment by DzhideX** [comment]
Great find on the webpack fix and thank you for taking the time to take care of this!

One little thing I'd love for you to quickly update is the `@joystream/types` version to the [current one](https://github.com/Joystream/joystream/blob/4bd3d2438ba28021407c992752390aeced6fb03f/types/package.json#L3) `^0.17.2`. After that we can get this merged!

**Comment by freakstatic** [comment]
> 

Oh didn't notice there was already a newer version, updated!
Please check now

**Comment by DzhideX** [comment]
Yeah, I've been playing around with this for a bit now. Initially I found this storybook failure weird but thought it might be one of those weird errors that should be fixable with a redeployment. Nevertheless, I took a look at running storybook locally and now there's a couple of errors there that I've been trying to fix.

**Comment by freakstatic** [comment]
> Yeah, I've been playing around with this for a bit now. Initially I found this storybook failure weird but thought it might be one of those weird errors that should be fixable with a redeployment. Nevertheless, I took a look at running storybook locally and now there's a couple of errors there that I've been trying to fix.

`yarn storybook` runs fine here, it shows some warning but they go away with this config on `.babelrc `


`{
  "presets": ["babel-preset-gatsby"],
  "plugins": [
    [
      "prismjs",
      {
        "languages": ["javascript", "css", "markup", "graphql"],
        "plugins": ["normalize-whitespace"],
        "theme": "okaidia",
        "css": true
      }
    ],
    ["@babel/plugin-proposal-private-property-in-object", { "loose": false }]
  ]
}
`

**Comment by freakstatic** [comment]
> > Yeah, I've been playing around with this for a bit now. Initially I found this storybook failure weird but thought it might be one of those weird errors that should be fixable with a redeployment. Nevertheless, I took a look at running storybook locally and now there's a couple of errors there that I've been trying to fix.
> 
> `yarn storybook` runs fine here, it shows some warning but they go away with this config on `.babelrc `
> 
> ```
> {
>   "presets": ["babel-preset-gatsby"],
>   "plugins": [
>     [
>       "prismjs",
>       {
>         "languages": ["javascript", "css", "markup", "graphql"],
>         "plugins": ["normalize-whitespace"],
>         "theme": "okaidia",
>         "css": true
>       }
>     ],
>     ["@babel/plugin-proposal-private-property-in-object", { "loose": false }]
>   ]
> }
> ```

ok this is not a good idea since it breaks `yarn build`

**Comment by DzhideX** [comment]
Update: It seems @traumschule had the same problem as we are having here (in https://github.com/Joystream/joystream/issues/3121) and [the PR fix](https://github.com/Joystream/joystream/pull/3134) has already been made. I've already gone and tested it and indeed it does work perfectly. 

Now, since FM form won't be used any longer I propose we wait until the new type version is published and use that. Would you be fine with taking that up? (If not, I wouldn't mind doing it myself :+1:)

**Comment by freakstatic** [comment]
> Update: It seems @traumschule had the same problem as we are having here (in [Joystream/joystream#3121](https://github.com/Joystream/joystream/issues/3121)) and [the PR fix](https://github.com/Joystream/joystream/pull/3134) has already been made. I've already gone and tested it and indeed it does work perfectly.
> 
> Now, since FM form won't be used any longer I propose we wait until the new type version is published and use that. Would you be fine with taking that up? (If not, I wouldn't mind doing it myself +1)

oh interesting!
yeah I don't mind taking that up, let's wait then

**Comment by DzhideX** [comment]
I think the new version of `@joystream/types` is live. Can you try again when you have the time?

**Comment by freakstatic** [comment]
> I think the new version of `@joystream/types` is live. Can you try again when you have the time?

thanks for notifying! 
just tried and seems good! 
changes commited!

**Review by DzhideX — APPROVED** [review]
Great work. Thank you!

**Pull request merged**
