### PR TITLE
Interactive Founding Members Form

### PR DESCRIPTION
**Pull request by DzhideX**
This is a work in progress, currently implemented:
- Scoring Round Selection [hardcoded values for now]
- Implement base for all new form views (Council, Roles, Validator, etc.)

### CODE REVIEW

**Comment by bwhm** [comment]
Great start!

Notes below :)

### General
- Update the carousel(?) to:
  1. Account info
  2. Data
  3. Summary (eg. show everything, and something like "if this looks ok...")
  4. Key file and signature
  5. Accept terms & conditions

### Dropdowns
- Can the fonts in the dropdown be changed to "our"?
- Bakground color of dropdowns should be in the color palette

### 2. Data
- "Select Round" -> "Select Scoring Period"
  - shouldn't accept the current period
- "Summary Type" and next gives me the impression that you have to choose pr submission
  - can you autoload the input fields without after choosing from the dropdown without clicking next?
  - keep the scoring period set, so that when you add more data, you can't change this
- As you add more stuff, would it be possible to display the data you already added below? Could just be the .json as a starting point
  - if not, add an "undo" button
- Provide an overview once you're done, and let users make changes


#### Validator
- "Are your stash and controller key the same?" -> "Is your Validator stash key the same as your membership controller`*`"
  - `*`Or is it root?
- If "No":
  - Add a link to where they can sign
  - Make it clear that they are signing with their Validator `stash`, not their membership controller/root key!

#### Council

Screen Shot 2021-07-19 at 17 33 22

1. I don't know exactly how to do this, but I think it needs to give them two options, where the following is displayed (read from the fm-info.json):
- the block range of the terms (eg 1-1337)
- the date range of the terms
- an `ID` that corresponds to the [blog](https://blog.joystream.org/sumer-kpis)
- dates. As many will have participated in two Councils, I think we should also consider separate them. So if you choose both, you'll have to fill in twice...

2. Come to think of it, we should probably skip this one.  

3. "Proposal IDs" -> "Comma-separated list of any relevant Proposal IDs". Optional.

4. "Forum contact information" is not correct. This should be an array of links, with the more descriptive: "Optionally, provide relevant links from the forum, github or discord". Might work with a comma-separated list, but ideally not. Still, start there?

5. "Extra information" -> "Any additional information?". Optional


#### Roles

Screen Shot 2021-07-19 at 17 48 37

1. Default to Scoring Periods start and end blocks
  - Make it clear that this refers when the user was hired and when they were fired or quit. It should only be changed if they weren't in the role the entire Scoring Period.

2. "Proposal IDs" -> "Comma-separated list of any relevant Proposal IDs". Optional.

3. "Forum contact information" is not correct. See above

4. "Extra information" -> "Any additional information?" Optional


#### Content Bounties

Screen Shot 2021-07-19 at 17 45 11

1. "Proposal IDs" -> "Comma-separated list of the relevant Proposal IDs". (Not Optional).

2. "Forum contact information" is not correct. See above

3. "Video links" -> "Comma-separated list of all the qualifying Video IDs"

4. Total ($) reward for the Bounty

5. Add this "Extra information" -> "Any additional information?" Optional

#### Bounties

Screen Shot 2021-07-19 at 17 40 17


1. "Proposal IDs" -> "Comma-separated list of the relevant Proposal IDs". (Not Optional).

2. "Forum contact information" is not correct. See above

3. Total ($) reward for the Bounty

4. "Extra information" -> "Any additional information?" Optional


#### Other

Screen Shot 2021-07-19 at 17 56 33

1. "Action information" -> "Explain in short what you did"

2. Should again be a list of comma separated links.


### 3. Summary
- As stated above, show a preview, and allow the user to edit.

### 4. Key file and signature
- Same as before

### 5. Accept terms & conditions
- Same as before

---

Let me know how you want the data to be presented in the `fm-info.json` file!

**Comment by DzhideX** [comment]
I think it's time for another review. For the most part, all of the suggestions should be implemented. If you have any more things you'd like to add that we didn't talk about or that I may have overlooked, please do! There are some things that I would like to add myself:

**Questions:**
 - Currently, only one instance of a role is allowed per scoring period [i.e you can't have two for storage] as I think only one person can only have one account. Is that correct?
 - I've noticed a referrer property on the shared file. How is this to be handled? (Is it still necessary?)
 - The data overviews are currently in json form. I don't mind how it looks but it may confuse others, do you have an idea on what should be done?
 
**Notes:**
- Dropdowns as they are are very, very difficult to style and almost impossibly so when taking into account all the different browsers ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#styling_with_css)). The only thing we can really style is the base look and the rest is going to look different based on different browsers. If we really want to style the dropdowns a lot, we can opt to install a library that does this or make our own dropdown (this would take a while..).
- After adding another tab, the progress bar at the top has become overcrowded. I've shrunk the padding on the sides and renamed some of them to better fit but I would love your input on these!

**Review by bwhm — CHANGES_REQUESTED** [review]
Looking great!

Some small remaining notes from me:
- Add an "edit" button, along with "Add more data" and Continue to submission

**Validators**
1. When you have added one, the next will override the previous one. This is correct in the sense that you should only be "allowed" to do one, but perhaps include a warning?
2. More of a question, but when I add stash that isn't the same as the membership key, and provide an incorrect signature, clicking next doesn't work. I assume you are validating it? All of this is good of course, but an error would make it easier for the user!


**Council**
1. Remove the "Contact information..." from the links field.
2. Maybe scrap the `Optionally` now that it's clear what is mandatory.
These two applies to most "Types" btw.

**Working Group**
1. For "Start block" and "End Block", make it clear that you should only change these if you were hired or fired during the scoring period.

**Comment by bwhm** [comment]
@blrhc 
You have seen more of these than anyone else, perhaps you can provide some insight? Can test here:
https://deploy-preview-369--joystreamdevelopment.netlify.app/founding-members/form/

**Comment by blrhc** [comment]
> https://deploy-preview-369--joystreamdevelopment.netlify.app/founding-members/form/

I will take a look and offer some suggestions as soon as possible.

**Comment by blrhc** [comment]
@DzhideX Sorry for the delay in reviewing this.

Honestly, I think this is excellent work, will definitely make everything a lot more efficient to grade!

I have a couple of points:

- I think a back button in various places would help out a lot, when testing it out it was quite frustrating to have to refresh the page and return to the key upload process if I made a mistake (resulting in losing all the data entered so far).

- People should be able to choose either Validator or Node operator, as they're basically two variants of the same activity. As a result, they shouldn't be able to claim for both of these within the same round - this should be made clear on the form for each of these activities.

- At the beginning of the process, it should be made clear that you can report for more than one scoring period and more than one type of activity before submitting the form.

- The "How it works" link at the start can be removed, the form should now be self-explanatory, and the information linked to isn't very clear in any case.

- It seems to be the case that information can be overwritten in various places, perhaps just make it clear when someone has already submitted a certain part of the form, and they're just replacing what's already in the JSON?

- I'm not too keen on the Bounties and Content Bounties being separate on the dropdown. Might it be possible to add a yes/no question after selecting bounties if people want to specify that it's a content bounty?

- Please could you add the following contribution categories in addition to the ones listed:
  - Creative or Graphic Design
  - Community Support*
  - Bug Reporting**
  - Tool Development
  - Documentation
  - Blog Posts
  - Original Video Production***

For now, each of these categories can just have a textarea that asks them to describe their activity
`* community support should ask with a radio input whether support was on Discord or Telegram`
`** should also ask for a link to GitHub or Discord where the bug report was made`
`*** should make clear that only exceptionally high-quality original videos which have not already been rewarded under a public bounty will qualify.`

Thanks again for creating this, excellent work.
These are just suggestions really, please let me know if you disagree!

**Comment by DzhideX** [comment]
I think this can be closed now?

**Comment by DzhideX** [comment]
I was initially wondering where I read this but finally found it again: https://github.com/Joystream/joystream-org/issues/431

Since it's being removed, I'll close this as well!

**Pull request closed without merging**
