### PR TITLE
New landing page

### PR DESCRIPTION
**Pull request by DzhideX**
Aims to implement the new landing page redesign for joystream-org (ref.issue: https://github.com/Joystream/marketing/issues/267).

One thing to note, the library used for the carousel found in "Our Investors" section can not accommodate a stopping of the carousel on hover. While doing research on these before I've had a hard time finding a good carousel library that is also performant and comfortable to use. Due to the time constraint I suggest we leave this implementation as is and then I can implement my own carousels during the second part of the implementation.

Questions:
- What link should we use for "Sign up for beta tests ->"? Same question for FM program and FAQ in the footer?
- It seems that we have Telegram in the footer instead of Discord, I assume that's a remnant of a previous implementation?

Any comments/ideas/tips are very welcome!

### CODE REVIEW

**Comment by bedeho** [comment]
1. Fantastic work @DzhideX , and thanks for the fast turnaround.
2. It really seems like the gab between a few of the sections is way too small, and smaller than the design. Best example is between NFT section and Chris Dixon blurb, but also others. Can we fix the design and/or markup here?
3. Please add "Learn More" button which exists on the original site.
4. I think we can just merge in Primer, and add it to menu as well. Its like 40% of the quality we want, but its still net positive.
5. One thing that really stunned me here was the _pure assult_ of the GDPR banner on the overall design here, would it be possible to harmonize the two and make the least intrusive and compliant version we can have? playing both with colors, size, location, etc.

Screenshot 2022-08-05 at 08 49 32

**Comment by dmtrjsg** [comment]
@toiletgranny @DzhideX 

it looks like image assets are a bit low res:

Screenshot 2022-08-05 at 08 17 54

Screenshot 2022-08-05 at 08 18 24

I'll get back to you on beta testing link!

**Comment by toiletgranny** [comment]
Alright, now that was super fast! It's so exciting to see this thing coming alive with such attention to detail, @DzhideX, thank you, thank you, thank you! ❤️

When going through the implementation, I noticed the lack of a few sections we have in the designs, such as blue blocks with CTAs and YPP mentions or carousels with the recently paid-out channels and sold NFTs. Is the goal to have them added at a later stage? If so, it would be awesome also to have an opportunity to review those once ready.

----

In regards to the animations, I really like where we are at right now!
1. I noticed we're using some sort of limit, after which the parallax effect is no longer working. I understand the intention here was to have the visuals look 1:1 in our mockups at some point, but I wonder if we could drop this limit entirely. Or perhaps, if we need to keep it, increase the intensity of the parallax. Happy to discuss this over a quick Slack call, I know it's much easier this way with these things!
2. Now that we haven't implemented the interactive glass effect, I wonder if there's an easy way to compensate for the lost interactivity, and I thought of using some simple entry CSS animations. For example, with this [AOS - Animate on scroll library](http://michalsnik.github.io/aos/) by Michał Sajnóg, which is incredibly easy to set up and customize. Let me know if you think that's feasible. Again, happy to discuss on Slack!

I did also find some minor visual bugs, which are invetiable when implementing such a diverse and rich LP. These are mostly tiny details, which — hopefully — are really easy to fix. 

1. Seems like we don't have @2x versions of images, which makes them blurry on retina displays. If image size was the concern, perhaps we could try out converting them to webp? Happy to talk this through on Slack and support in exporting the right assets from Figma.
2. Distance between the "Built on Joystream blockchain and managed by the DAO community." and the button is set to `66px`, should be `48px`.
3. The bottom padding in the hero section is currently set to `92px`, should be `96px`, just like the top padding.
4. For accessibility reasons, I don't think we can have `<h3>` tags above the `<h2>` ones. Would that be possible to keep all blue titles as H2s and the larger headings below them as regular `<p>` or `<span>` tags?
7. Margin between text and illustration columns doesn't seem consistent across different sections. For example, in the Payouts section, it's `34px`, while in the Video NFTs section it's `30px`. `30px` is the gap between columns in the grid that's been used for Joystream.org historically, so I believe it's best to keep it at this value. It's a minor thing, but if there's an easy thing to fix it all, that would be great. 
8. Margin between the four features in the Creator Tokens section is set to `96px`, should be `64px`.
9. On mobile, the margin between heading and the body copy, in text these slightly smaller columns for Creator Tokens features, is set to `16px`, but it should be `8px`. [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5989%3A325645)
10. Both vertical and horizontal padding seems to be off on mobile in the Manifesto section. Can we have another look at it? [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5989%3A318489)
11. Seems like we missed adjusting vertical padding in the rewardable activities section. It's set to `150px`, but it should be `96px`, just like in other sections.
12. On mobile, in the rewardable activities section, the margin between the body copy and the grid of boxes with activities is set to `30px`. Should be `64px`.
13. The text column in the Joystream DAO section doesn't seem to be centered vertically, just like all other text columns placed next to a taller illustration.
14. Vertical padding in the Jsgenesis section is currently set to `125px`, it should be `128px`.
15. Vertical padding in the footer should, ideally, be set the same way as in all other sections, meaning `96px` for both top & bottom. Currently it's `120px` for the top and `100px` for the bottom.
16. The margin between the "Stay up to date", "Investors", and the links parts of the footer should be set to `96px`. Currently, it's a bit different for each part. 
8. Similar to the Manifesto section, both vertical and horizontal padding seems to be off on mobile in the footer. Can we have another look at it? [(Figma reference)](https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5965%3A280927)
17. Height of the navbar is currently set to `90px`. If we need to specify a fixed value, it should be `80px`, but — ideally — its height is driven by the contents inside and `16px` of top and bottom padding.

**Comment by toiletgranny** [comment]
@bedeho 

>It really seems like the gab between a few of the sections is way too small, and smaller than the design. Best example is between NFT section and Chris Dixon blurb, but also others. Can we fix the design and/or markup here?

I believe the reason you get this impression is that the implementation is still missing the `Recently sold NFT videos` that should normally be between these two elements. And while there are, indeed, some minor bugs in margins and paddings in the implementation, which I already pointed out above, in this case, I would maybe advise to just wait out for the stream of the recently sold video NFTs to get added here. 
CleanShot 2022-08-05 at 10 15 23


> One thing that really stunned me here was the pure assult of the GDPR banner on the overall design here, would it be possible to harmonize the two and make the least intrusive and compliant version we can have? playing both with colors, size, location, etc.

Oh, I feel you! I'm on it. @DzhideX I'll try to come up with an alt GDPR banner design that is not super far away from the current one, so that the implementation is as straightforward as possible. Will let you know once I have something for you on Slack.

**Comment by DzhideX** [comment]
@bedeho

1. Thank you, I'm glad you like it!

2. I agree with Adam down below that some sections probably look a bit off because of the sections we removed. I'll implement all of his suggestions and then maybe you can take another look and if you still dislike it you can pinpoint specific sections (along with the NFT section) you think still need more space?

3. I assume you mean in the one in the Navbar. Will do!

4. Okay!

5. Will follow up with Adam on this :+1:

**Comment by DzhideX** [comment]
@toiletgranny 

>Alright, now that was super fast! It's so exciting to see this thing coming alive with such attention to detail, @DzhideX, thank you, thank you, thank you! heart

I was hoping the implementation would meet your standards. Would be a shame to waste such a phenomenal design! :100:  (also, don't be shy with the criticism, I am happy to hear any suggestion/improvement you might have [but judging by the wall of text, I think you didn't :wink: ])

>When going through the implementation, I noticed the lack of a few sections we have in the designs, such as blue blocks with CTAs and YPP mentions or carousels with the recently paid-out channels and sold NFTs. Is the goal to have them added at a later stage? If so, it would be awesome also to have an opportunity to review those once ready.

Indeed! Will let you know when those are ready.

>I noticed we're using some sort of limit, after which the parallax effect is no longer working. I understand the intention here was to have the visuals look 1:1 in our mockups at some point, but I wonder if we could drop this limit entirely. Or perhaps, if we need to keep it, increase the intensity of the parallax. Happy to discuss this over a quick Slack call, I know it's much easier this way with these things!

Ooh, we can do that for sure! I think it might be beneficial to jump on a quick call and have us go through a couple (or all of them together) so I can get a full idea of what you mean exactly (even though I *think* I have a good idea atm)!

>Now that we haven't implemented the interactive glass effect, I wonder if there's an easy way to compensate for the lost interactivity, and I thought of using some simple entry CSS animations. For example, with this [AOS - Animate on scroll library](http://michalsnik.github.io/aos/) by Michał Sajnóg, which is incredibly easy to set up and customize. Let me know if you think that's feasible. Again, happy to discuss on Slack!

We can add this to the call agenda too!

> I did also find some minor visual bugs, which are invetiable when implementing such a diverse and rich LP. These are mostly tiny details, which — hopefully — are really easy to fix.

Awesome, thank you for the detailed look, I'll go through all of this and try my best to fix them! As said above, if you have any other comments do let me know.

**Comment by dmtrjsg** [comment]
++ as discussed

1. Remove "Sign up for Beta testing" on CRTs section
2. Remove Youtube sync section as visuals are not prepared

@toiletgranny cc

**Pull request merged**
