### PR TITLE
Landing page update

### PR DESCRIPTION
**Pull request by DzhideX**
This PR aims to implement the design outlined here: https://github.com/Joystream/joystream-org/issues/651

Notes:
- The current implementation only takes into account the design and accommodates the lack of data with placeholders (i.e., the token metrics price graph).
- A placeholder video was used for the "Our Vision" section.
- Some placeholder content needs updating (e.g., tooltips, new apps added in the ecosystem section)
- There are missing URLs for some of the new links/buttons.

Questions:
- For the hero button, the dashboard is not yet implemented. Do we want to remove it temporarily or have it link somewhere else?

### CODE REVIEW

**Comment by KubaMikolajczyk** [comment]
Hey @DzhideX the Job you did is phenomenal 🤯 I know the list below is big - but its still the best implementation of design that I had a chance to check for months already - big big kudos to you for the attention to detail when it comes to padding and margins. Thank you sir ⭐️ If I could give any feedback here I can see that main errors are related with elements using grid system this may be a field for improvement (but even here its improved a lot). 

Below everything I could find:

# Overall

## 1. Key hero Background
image
On the preview which Im using I can clearly see the tiles rotating in the background where it should be a smooth gradient rotating around

## 1a. Key hero title
image
Is there a way to get a line which is not bolded like the rest of the font is?

## 2. Joystream creators, recent rewards, recent proposals
image
I was unable to review them due to the fact that there is no dummy data for me to see the cards - could we add at least 6 items of dummy data for each carousel so I can check them too?

## 3. Steps
image
Lets make them all equal height so we have the effect of steps not only visible on the top of cards but also on the bottom like in designs
image

## 4. Grid alignment
image
In the section above (1400px) the elements inside do not fill the 12 columns instead those are probably using fixed width

## 4a. creator monetization 
image
The illustration should have 7 columns of width while text should use 5

## 5. Margin auto on illustrations
image
I propose to rework all illustrations and images in such way that they fill the width of their container and then just keep the aspect ratio that they are prepared in - so no auto margins - resizing with grid and keeping the ratio

## 6. Builders grant section
image
We have only 3 user avatars displayed instead of 5 where two on each side should have sligtly lowered opacity. Additionally the sign up for program label is wrapped in two lines

## 7. Scaling above 1440px
There should be no more scaling above 1440px for the most of UI - only background of sections but except that all of the sections should keep the 1440px size as fixed from LG breakpoint

# RWD - listed by sections
## Hero section
### XXS
1. Border radius of the key hero container should be 24px on this breakpoint
### XS
image
1. After scaling from XS to SM the top illustration is not displayed fully
image
image
2. It looks like the top title does not fill the container but uses fixed width
### SM
image
3. Same thing when scaling from SM up - title is not using the space and the illustration is cut in half
### MD
image
1. Same thing as above happens when scaling from MD up
### LG
image
image
1. The whole layout jumps at 1440px

## Our vision
### XXS
1. Not a mistake in implementation but could we change the size of the play "button" area in XXS and XS breakpoints to be always 64x40 - this is too small now for a trigger to an action - I already corrected the RWD - [Link](https://www.figma.com/file/dmmYGgpFwRyHJ9cueKiTUx/Homepage?type=design&node-id=9952-202970&mode=design&t=n9XSGnM8WiwWcGVi-4)

## Growth & Engagement
### XXS
image
1. The padding between the metric cards and Joystream Creators sub section should be equal to 48px now its double that and the padding between that and the end of the whole section should be 64px now its 48px
### MD
image
1. It looks like there is a huge additional bottom gap below the cards which shouldnt be here

## Token Metrics
### XS
image
1. We would want ideally this graph to fill the whole container width when scaling
### SM
image
1. Something is wrong with card spacing here from this breakpoint?
### MD
image
1. Those cards dont fill the whole available space in height creating a larger vertical gap than 24px

## One Protocol, a Universe of Applications
### XXS
image
1. Space between the app logo of gleev and the featured label should be 40px not 64px
image
2. The carousel control presents only two steps while in reality we already have 5 apps there we have to add steps as now interacting with them scrolls you to the last app
image
3. Gap between button and illustration should be 48px
image
4. We might want to add the same type of carousel indicators below the steps
image
5. Gaps both vertical and horizontal on XXS, XS and SM breakpoints should be equal to 16px
image
6. This title on XXS should be H400 not h500 - its H500 from XS
### XS
image
1. Somtehing is wrong with spacing from this breakpoint here?
### SM 
image
1. This section is not scaling SM up with the columns its using fixed width
### MD
image
image
1. This is not using the grid system

## Powerful New Value Capture Tools
### XXS
image
1. Space between Payouts sub section and the recent rewards carousel should be equal to 56on XXS and XS breakpoints - its my mistake! I already corrected that in RWD
image
2. Top margin here should be also 56 not 72px
### SM
image
1. This section is not scaling with grid columns when scaling from SM up its fixed width
### MD
image
image
image
1. This is not using the grid system
image
2. Those images have some problem with scaling and keeping ratio

`10 point to gryffindor if you have read all of this above 😅`

**Comment by bedeho** [comment]
This looks awesome! great work @KubaMikolajczyk and @DzhideX . Here are two cents from me

# scrollbar on apps menu

This looks bad, can we add a carousel buttons instead of scroller?

Screenshot 2023-11-16 at 21 30 06

# video

opening and starting playback took forever, can we just start playback without opening a cinema mode, and also is there some sort of setting which causes the video to buffer when the page loads, so playback is as low latency to start as possible. Also, great if you can already now start using correct video, do we need to upload it somewhere?

Screenshot 2023-11-16 at 21 30 29

**Comment by DzhideX** [comment]
@KubaMikolajczyk thank you for your detailed review. I went through all of your points (except things I mention below), let me know if it looks good now!

Notes:
- All the ones I didn’t mention I fixed. Also added placeholder data for graph and creators carousel.
- 1: As you initially suggested I just copied the functionality directly from ypp. It seems that some browsers have issues with rendering it correctly (in both instances), chrome works perfectly on my end. I tried looking into possible workarounds but I haven’t found any. Thoughts?
- 6: I can’t replicate the missing avatar bug (tested in Chrome, Firefox, Safari). Fixed text wrapping issue.
- RWD Hero title: The reasoning I used fixed width for the title here is because of the same layout jump that I missed in your last point. Fixed width was the only solution I could come up with.  I’m thinking, if it looks weird on certain parts of the breakpoints maybe it makes sense to add more breakpoints for that. Maybe you have a different idea?
- One Protocol, a Universe of Applications: I don’t think that this carousel should have 5 controls at all time. At desktop sizes the last 2 wouldn’t do anything (if we assume every control moves to a unique item ~ this is due to the amount of items shown on desktop compared to mobile). As a solution I made it dynamic, there’s 3 on desktop and it increases based on the amount shown at any time. So, on mobile it shows 5 and desktop 3 (there’s also 4 in between as well). Is that alright?

**Comment by DzhideX** [comment]
Some important notes on what else is missing/needs updating on the page:
- Hero button points to old location. What do we want to do with it?
- Traction info tooltips have lorem ipsum placeholder text.
- Tokenomics info tooltips have lorem ipsum placeholder text.
- All apps (except gleev and l1media) in ecosystem section have placeholder descriptions.
- Upcoming section link is empty.

**Review by bedeho — APPROVED** [review]

**Pull request merged**
